"""empty message

Revision ID: 771994eca812
Revises: 
Create Date: 2026-01-18 10:42:43.201490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771994eca812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_master_login_id'), ['login_id'], unique=True)

    op.create_table('task_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PENDING', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_name', name='_user_task_unique')
    )
    with op.batch_alter_table('task_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_table_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_table_user_id'))

    op.drop_table('task_table')
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_master_login_id'))

    op.drop_table('user_master')
    # ### end Alembic commands ###
